# Generated by Django 5.2.7 on 2025-12-11 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_diagnosis_top_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='review_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('edited', 'Edited by vet')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_treatment', 'Under Treatment'), ('resolved', 'Resolved'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('edited', 'Edited')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='DiagnosisAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='api.diagnosis')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
